"""
JARVIS v2 — tools/report_gen.py

Auto report generator. Commands:
  export last          Save last response as markdown
  export report        Generate report from last workflow
  export memory        Export memory as JSON
"""
import json
from datetime import datetime
from pathlib import Path
from rich.console import Console
from rich.text import Text

REPORTS_DIR = Path("reports")
REPORTS_DIR.mkdir(exist_ok=True)


class ReportGenerator:
    def __init__(self, console: Console, memory):
        self.console = console
        self.memory = memory

    def export_last(self, last_output: str, last_skill: str = None) -> str:
        """Save last response as markdown."""
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"report_{ts}.md"
        filepath = REPORTS_DIR / filename

        report = f"""# Jarvis Report
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Skill:** {last_skill or 'direct'}

---

{last_output}

---
*Generated by JARVIS v2*
"""
        filepath.write_text(report)
        self.console.print(f"  [bold #10b981]✓ Saved:[/bold #10b981] {filepath}\n")
        return str(filepath)

    def export_memory(self, fmt: str = "json") -> str:
        """Export memory as JSON."""
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")

        episodes = self.memory._conn.execute(
            "SELECT id, ts, role, task, skill, outcome, duration, profile "
            "FROM episodes ORDER BY id"
        ).fetchall()

        stats = self.memory._conn.execute(
            "SELECT skill, uses, success FROM stats ORDER BY uses DESC"
        ).fetchall()

        data = {
            "exported_at": datetime.now().isoformat(),
            "episodes": [
                {"id": r[0], "ts": r[1], "role": r[2], "task": r[3],
                 "skill": r[4], "outcome": r[5], "duration": r[6], "profile": r[7]}
                for r in episodes
            ],
            "stats": [
                {"skill": r[0], "uses": r[1], "success": r[2]}
                for r in stats
            ],
        }

        filepath = REPORTS_DIR / f"memory_export_{ts}.json"
        filepath.write_text(json.dumps(data, indent=2))
        self.console.print(f"  [bold #10b981]✓ Exported:[/bold #10b981] {filepath}")
        self.console.print(f"  [dim]{len(episodes)} episodes, {len(stats)} skills[/dim]\n")
        return str(filepath)


EXPORT_PREFIXES = ("export ",)

def is_export_command(query: str) -> bool:
    return query.lower().strip().startswith("export ")
